name: blupr
description: A personal Linux image built atop silverblue with Hyprland as a window manager.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41
modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
    install:
      - wofi
      - power-profiles-daemon
      - xorg-x11-server-Xwayland
      - polkit
      - xfce-polkit
      - xdg-user-dirs
      - dbus-tools
      - dbus-daemon
      - wl-clipboard
      - pavucontrol
      - playerctl
      - qt5-qtwayland
      - qt6-qtwayland
      - vulkan-validation-layers
      - vulkan-tools
      - google-noto-emoji-fonts
      - gnome-disk-utility
      - ddcutil
      - wireplumber
      - pipewire
      - pamixer
      - pulseaudio-utils
      - network-manager-applet
      - NetworkManager-openvpn
      - NetworkManager-openconnect
      - bluez
      - bluez-tools
      - blueman
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - xarchiver
      - imv
      - p7zip
      - unrar
      - gvfs-mtp
      - gvfs-gphoto2
      - gvfs-smb
      - gvfs-nfs
      - gvfs-fuse
      - gvfs-archive
      - android-tools
      - zathura
      - slurp
      - grim
      - wlr-randr
      - wlsunset
      - brightnessctl
      - hyprlock
      - hypridle
      - swww
      - waypaper
      - wlogout
      - kanshi
      - cava
      - kitty
      - fastfetch
      - mako
      - adwaita-qt5
      - fontawesome-fonts-all
      - gnome-themes-extra
      - gnome-icon-theme
      - paper-icon-theme
      - breeze-icon-theme
      - papirus-icon-theme
      - lxappearance
      - hyprland
      - waybar
      - xdg-desktop-portal-hyprland
      - brightnessctl
    remove:
      - firefox
      - firefox-langpacks
  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: Flathub (system-wide)
      install:
        - org.mozilla.firefox
        - io.mpv.Mpv
        - org.localsend.localsend_app
        - com.stremio.Stremio
        - org.telegram.desktop
        - io.github.flattool.Warehouse
        - de.haeckerfelix.Shortwave
        - com.github.neithern.g4music
        - org.deluge_torrent.deluge
        - org.gimp.GIMP
        - com.interversehq.qView
        - com.usebottles.bottles
        - dev.zed.Zed
        - org.kde.kdenlive
        - org.upscayl.Upscayl
        - org.onlyoffice.desktopeditors
        - org.nickvision.tubeconverter
        - com.notesnook.Notesnook
        - com.github.finefindus.eyedropper
      remove: null
  - type: signing
