# image will be published to ghcr.io/<user>/<name>
name: bluiri
# description will be included in the image's metadata
description: A personal Linux image built atop silverblue with Niri as a window manager.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files 
    files: # what is in /etc/skel/ gets copied to a newly created user’s $HOME automatically after rebooting 
      - homedir: /usr/etc/skel
      - usr: /usr
        
  - type: rpm-ostree
    repos: 
      # hyprland
      # - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      # niri
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-41/yalter-niri-fedora-41.repo

    install:
      # launcher
      - fuzzel
      # environment
      - xorg-x11-server-Xwayland
      - polkit
      - xfce-polkit 
      - xdg-user-dirs
      - dbus-tools
      - dbus-daemon
      - wl-clipboard
      - pavucontrol
      - playerctl
      - qt5-qtwayland
      - qt6-qtwayland
      - vulkan-validation-layers
      - vulkan-tools
      - google-noto-emoji-fonts
      - gnome-disk-utility
      - ddcutil
      # sound
      - wireplumber
      - pipewire
      - pamixer
      - pulseaudio-utils
      # networking
      - network-manager-applet
      - NetworkManager-openvpn
      - NetworkManager-openconnect
      - bluez
      - bluez-tools
      - blueman
      # file manager
      - thunar
      - thunar-archive-plugin 
      - thunar-volman
      - xarchiver
      - imv
      - p7zip
      - unrar
      - gvfs-mtp
      - gvfs-gphoto2
      - gvfs-smb
      - gvfs-nfs
      - gvfs-fuse
      - gvfs-archive
      - android-tools
      - zathura
      # screenshot
      # - slurp
      # - grim
      # display
      - wlr-randr
      - wlsunset
      - brightnessctl
      - hyprlock
      - hypridle
      - wlogout
      - kanshi
      - cava
      # terminal
      - fastfetch
      - htop
      # notifications
      - dunst
      # theme and GUI
      - fontawesome-fonts-all
      - gnome-themes-extra
      - gnome-icon-theme
      - paper-icon-theme
      - breeze-icon-theme 
      - papirus-icon-theme
      - lxappearance
      - swaybg
      # wm
      - kitty
      - geany
      - niri
      - waybar
      # - xdg-desktop-portal-hyprland
      - brightnessctl

    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        - org.videolan.VLC
        - me.timschneeberger.jdsp4linux
        - org.localsend.localsend_app
        - com.stremio.Stremio
        - org.telegram.desktop
        - io.github.flattool.Warehouse
        - org.feichtmeier.Musicpod
        - com.transmissionbt.Transmission
        - com.interversehq.qView
        - com.usebottles.bottles
        - dev.zed.Zed
        - org.onlyoffice.desktopeditors
       
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
